language: node_js

node_js:
  - "stable"
    
cache: [node_modules]

script:
  - npm run test -- --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
 
# before_install:
#   - cd server

